# Generated by Django 5.2.1 on 2025-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="rights",
            field=models.CharField(default="User", max_length=20),
        ),
    ]
