# Generated by Django 5.2.1 on 2025-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dname", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("qualification", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_images/"
                    ),
                ),
            ],
        ),
    ]
