# Generated by Django 5.2.1 on 2025-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
