# Generated by Django 5.2.1 on 2025-05-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_doctor_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="myapp.hospital",
            ),
        ),
    ]
