# Generated by Django 5.2.1 on 2025-05-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(null=True),
        ),
    ]
