from django.urls import path
from . import views

urlpatterns = [
    path("",views.index),
    path("user_login/", views.user_login, name="user_login"),
    path("hospital_login/", views.hospital_login, name="hospital_login"),
    path("user_reg/", views.user_reg, name="user_reg"),
    # path("hospital_reg/", views.hospital_reg, name="hospital_reg"),
    path("user/", views.user, name="user"),
    path("hospital/", views.hospital, name="hospital"),
    path("users/", views.users, name="users"),
    path("block_user/<int:id>/", views.block_user, name="block_user"),
    path("unblock_user/<int:id>/", views.unblock_user, name="unblock_user"),
    path("view_department/", views.view_department, name="view_department"),
    path("add_department/", views.add_department, name="add_department"),
    path("edit_department/<id>/", views.edit_department, name="edit_department"),
    path("delete_department/<id>/", views.delete_department, name="delete_department"),
    path("manage_doctor/", views.manage_doctor, name="manage_doctor"),
    path("add_doctor/", views.add_doctor, name="add_doctor"),
    path("edit_doctor/<id>/", views.edit_doctor, name="edit_doctor"),
    path("delete_doctor/<id>/", views.delete_doctor, name="delete_doctor"),
    path("book_appointment/", views.book_appointment, name="book_appointment"),
    path('get_doctors/<str:department>/', views.get_doctors, name='get_doctors'),
    path('payment/<id>/', views.payment, name='payment'),
    path('my_appointments/', views.my_appointments, name='my_appointments'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('appointments/', views.appointments, name='appointments'),
    path('approve_appointment/<int:id>/', views.approve_appointment, name='approve_appointment'),
    path('approve_appointment/<int:id>/', views.approve_appointment, name='approve_appointment'),
    path('admit_patient/<int:id>/', views.admit_patient, name='admit_patient'),
    path('discharge_patient/<int:id>/', views.discharge_patient, name='discharge_patient'),
    path('complete_appointment/<int:id>/', views.complete_appointment, name='complete_appointment'),
    path('patients/', views.patients, name='patients'),
    path('hospital_profile/', views.hospital_profile, name='hospital_profile'),
]